import type { Metadata } from "next";

import Sidebar from "@/components/Sidebar";
import DashboardNavbar from "@/components/DashboardNav";


export const metadata: Metadata = {
    title: "Facebook Marketing",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body>
                <DashboardNavbar />

                <div className='lg:flex w-full lg:flex-row md:flex md:flex-col-reverse flex flex-col-reverse overflow-x-hidden'>
                    <div className="lg:w-1/2 md:w-full w-full 2xl:w-1/2">
                    <Sidebar />
                    </div>
                    <div className="w-full bg-muted sticky top-0">{children}</div>
                </div>
            </body>
        </html>
    );
}
