import type { Metadata } from "next";

import Sidebar from "@/components/Sidebar";
import DashboardNavbar from "@/components/DashboardNav";


export const metadata: Metadata = {
    title: "Landing Page design",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body>
                <DashboardNavbar />
                <div className='lg:flex lg:flex-row md:flex md:flex-col-reverse flex flex-col-reverse'>
                    <div className="lg:w-1/3 md:w-full w-full">
                    <Sidebar />
                    </div>
                    <div className="w-full bg-muted sticky top-0">{children}</div>
                </div>
            </body>
        </html>
    );
}
