import type { Metadata } from "next";
import { Inter, Poppins, Hind_Siliguri} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: "400", subsets: ["latin"] });
const hindSiliguri = Hind_Siliguri({ weight: ["300","400","500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Typing Mastery Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={hindSiliguri.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
